### ISSUE TITLE
no printer in the drop down menu 

### ISSUE THREAD

**Issue by erbyTV** [StewM/streamlabs-donations-printer#2]
I have a working printer connected to my pc but I cant figure out how to get it to be detected by the app? any suggestions?

**Comment by StewM** [comment]
Hmm I'm not sure. I'm using a third party library that's using sumatrapdf for all the printer interactions. I've also only tested on windows 10.  Does it show the built in pdf printer or any of the windows virtual printers in the dropdown?

**Comment by erbyTV** [comment]
Nope none at all. It just says the default. I tried changing my printers security and which apps could interact with it and stuff but never got anything to change

**Comment by erbyTV** [comment]
I decided to buy a usb connection cable for my printer instead of using wifi to see if that would change anything and it still doesn't give me any printers to choose from.

**Comment by StewM** [comment]
Hey, so I just pushed an update that pulled in a newer version of the printing library I'm using. The build should hopefully be done in a few minutes. I'm not sure it will actually help with this but it can't hurt.

I also looked into what the library is doing to get the list of printers. It's calling a built in windows command called wmic to get the printers. So you could try calling that directly just to see what your system is returning. The exact command that you would put into your command prompt is `wmic printer get name` which should return a list of all the printers your system can see. On my system I can see the various virtual printers I have on my system as well as my wifi printer, which is the exact same list I see in the app.

**Comment by erbyTV** [comment]
dude!! that was the issue! wmic was missing on my computer. I had to go manually add it back in and it worked.
